---
- hosts: sweethosts
  roles:
     - { role: scspclient1, objnumb: "100", nbrthreads: "10", objsize: "2000000000"  }
- hosts: sweeterhosts
  roles:
     - { role: scspclient2, objnumb: "100", nbrthreads: "10", objsize: "2000000000"  }
