---
 - name: yum-clean-metadata
   command: yum clean metadata
   args:
    warn: no

 - name: install s3cmd
   yum: 
    name: s3cmd
    state: latest

 - name: Adds s3 credentials
   template: >
    src=../templates/s3cfg.j2
    dest=~{{ s3cmd_user }}/.s3cfg
    owner={{ s3cmd_user }}
    mode=600
